#:schema https://raw.githubusercontent.com/git-town/git-town/refs/heads/main/docs/git-town.schema.json

# See https://www.git-town.com/configuration-file for details

interactive = true

[branches]
contribution-regex = "^wip-.+"
feature-regex = "^working-.+"
main = "main"
order = "asc"
perennial-regex = "^version-.+"
unknown-type = "contribution"

[create]
new-branch-type = "contribution"
share-new-branches = "push"
stash = true

[propose]
breadcrumb = "branches"
breadcrumb-direction = "down"

[ship]
delete-tracking-branch = true
ignore-uncommitted = false
strategy = "fast-forward"

[sync]
auto-sync = true
detached = false
feature-strategy = "merge"
perennial-strategy = "ff-only"
prototype-strategy = "merge"
push-branches = true
push-hook = true
tags = true
upstream = true
